# Generated by Django 5.0.7 on 2024-07-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_reservation_cip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='children',
        ),
    ]
