# Generated by Django 5.0.7 on 2024-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_reservation_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'اقا'), ('Female', 'خانم')], default='male', max_length=6),
        ),
    ]
