# Generated by Django 5.0.7 on 2024-07-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_descriptions_passenger_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='descriptions',
            new_name='description',
        ),
    ]
