# Generated by Django 5.0.7 on 2024-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_passenger_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='flight_type',
            field=models.CharField(choices=[('outbound', 'outbound'), ('inbound', 'inbound')], max_length=8),
        ),
    ]
